### ISSUE TITLE
BrowserSync gets disconnected 

### ISSUE THREAD

**Issue by joseasv** [simiancraft/create-phaser-app#16]
I don't know if I'm doing something wrong but BrowserSync gets disconnected as soon as the page loads. In the Firefox console, just below the Phaser version (first line of console), I see the "[WDS] Disconnected!" message.

I knew something was up when I saved my changes and the browser didn't auto refresh.

**Comment by joseasv** [comment]
I'm on Windows but I develop using Vagrant. I've used many boilerplates with BrowserSync or Webpack dev tools without problems. Normally I test on Firefox. In Chrome I got this:

Failed to load resource: net::ERR_CONNECTION_RESET
webpack:///(webpack)-dev-server/client?:170 [WDS] Disconnected!

And this multiple times:

sockjs.js:1601 GET http://localhost:8080/sockjs-node/info?t=1529003337150 0 ()

**Comment by the-simian** [comment]
I bet @vantreeseba  knows whats up

**Comment by vantreeseba** [comment]
@joseasv Make sure that you have the ports exposed from vagrant (8080) so that the browser connects to both the html port and the WS port that browsersync needs.

**Comment by joseasv** [comment]
Yeah, I have those ports (8080 and 3000) forwarded.

**Comment by vantreeseba** [comment]
I just tested this locally and ran into the same issue, turns out browser sync and WDS don't play well if you host it on localhost.  

I just pushed a fix to master, try pulling that down and if it fixes it for you, we'll close this.

**Comment by the-simian** [comment]
hey @joseasv and @vantreeseba it looks like this is working now, but if it isn't just comment in here, we will reopen it.

So I think this is fixed in 0.0.6

**Comment by the-simian** [comment]
ref https://github.com/simiancraft/create-phaser-app/commit/bd9e4db2333697e9241897d68d3ce5676af4425f

**Comment by joseasv** [comment]
Sorry for the late reply. I was having problems on my end with Vagrant but I updated the Guest Additions and now BrowserSync is detecting file changes. Thanks for the quick fix!

**Comment by the-simian** [comment]
@joseasv Thanks for opening an issue! we're still working on this, so keep an eye on it!
