### ISSUE TITLE
Fix player collider (it seems to be shifted up)

### ISSUE THREAD

**Issue by the-simian** [simiancraft/create-phaser-app#23]

**Comment by GabeAtWork** [comment]
I can't seem to be able to debug the player collider as indicated here: http://labs.phaser.io/edit.html?src=src%5Cphysics%5Carcade%5Csimple%20body.js

I'm interested in how you can debug that sort of problem ^^

**Comment by the-simian** [comment]
@GabeAtWork yeah, I had the same problem! I even looked at this to see what was going on. I can tell the collider is too tall, but I'm not 100% sure why that's the case. Let me take another look with your comments in mind.

I sincerely appreciate all you help and input so far!

**Comment by GabeAtWork** [comment]
Sure! Thank *you* for working on this project in the first place! It makes it really easy for someone like me with JS/ES6 experience to delve into Phaser. I like working on it even if I can't do much, it allows me to pick the engine up little by little ^^

**Comment by the-simian** [comment]
I dropped a line in the html5 game dev forums http://www.html5gamedevs.com/topic/38408-phaser-3-debug-property-in-physics-not-drawing-debug-layer/

TBH I'm kind of stumped why its not drawing

**Comment by the-simian** [comment]
Well i figured out how to get the debug working, so I'm able to actually fix the colliders, now. I'm nto sure why but you can only specify one scene

**Comment by the-simian** [comment]
ok this is quick fixed, but I need to do the larger job of refactoring the animation

**Comment by the-simian** [comment]
this will get fixed the right way with the solution to #24 , I'll close it then

**Comment by the-simian** [comment]
fixed by #36
