### ISSUE TITLE
Use prettier automatically on pre-commit

### ISSUE THREAD

**Issue by GabeAtWork** [simiancraft/create-phaser-app#25]
Edit: I hadn't seen prettier was already on, I'll make a PR with husky in case you want this formatting to happen automatically pre-commit

**Comment by the-simian** [comment]
This is a good issue, and the PR was close to how I want to achieve this goal, but I'll do it slightly differently, so that its easier to change and there's only one file for enforcing style and linting rules.

**Comment by GabeAtWork** [comment]
Alright, I'm interested in such a solution actually ^^

**Comment by the-simian** [comment]
resolved by #29

**Comment by the-simian** [comment]
ok this works, and if you set your editor  to use eslint, should just autoformat. like if you use VS code set it to format on save, and also husky will format it

you can use `yarn pretty` anytime to run the fixes

**Comment by GabeAtWork** [comment]
I see, it's elegant! The reason I got to use `lint-staged` on work projects is that I use PhpStorm which, oddly, doesn't support running prettier (or eslint) on file write. I would largely prefer it would though ^^

**Comment by the-simian** [comment]
Makes sense, @GabeAtWork you might consider at least investigating VS Code. Its free and its very nice for working in es6. I cant speak to its php support. I do know that the other editor by jetbrains for js (webstorm) does have this stuff though.

glad you like the update!
