### ISSUE TITLE
Test framework integration?

### ISSUE THREAD

**Issue by GabeAtWork** [simiancraft/create-phaser-app#27]
I have limited experience with gamedev, but it seems to me integrating a test framework might be worth it, at least for testing ui (especially with React #18).

Jest seems to me like the most obvious option, seeing its quality and level of support.

If you think it's useful, I can open a PR that adds Jest integration (if #26 is validated, I can make tests run precommit as well).

**Comment by the-simian** [comment]
I am down with Jest! Lets use it. I'd love a PR for Jest

**Comment by GabeAtWork** [comment]
Ok! Do you think it's more pertinent to have all tests reside in a `test/` folder, or to have tests alongside files, à la React?

I use both at work, but I think I prefer the second approach. It makes sense for most unit tests and components tests to be in the same folder as the source file to me. And we can have integration tests in a separate folder if need be?

**Comment by GabeAtWork** [comment]
PR opened, I went with the second option for now, jest makes it real easy to relocate tests later if need be.

**Comment by the-simian** [comment]
Also, to answer your question I prefer the second approach as well, you just add test where is necessary
